// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: dbquery.sql

package dbq

import (
	"context"
)

const createTea = `-- name: CreateTea :one
INSERT INTO teas (
  teapod, collection, value
) VALUES (
  ?, ?, ?
)
RETURNING id, teapod, collection, resource, value, created, updated
`

type CreateTeaParams struct {
	Teapod     string
	Collection string
	Value      interface{}
}

func (q *Queries) CreateTea(ctx context.Context, arg CreateTeaParams) (Tea, error) {
	row := q.db.QueryRowContext(ctx, createTea, arg.Teapod, arg.Collection, arg.Value)
	var i Tea
	err := row.Scan(
		&i.ID,
		&i.Teapod,
		&i.Collection,
		&i.Resource,
		&i.Value,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteTea = `-- name: DeleteTea :exec
DELETE FROM teas
WHERE teapod = ? and resource = ?
`

type DeleteTeaParams struct {
	Teapod   string
	Resource string
}

func (q *Queries) DeleteTea(ctx context.Context, arg DeleteTeaParams) error {
	_, err := q.db.ExecContext(ctx, deleteTea, arg.Teapod, arg.Resource)
	return err
}

const getTea = `-- name: GetTea :one
SELECT id, teapod, collection, resource, value, created, updated FROM teas WHERE teapod = ? and resource = ? LIMIT 1
`

type GetTeaParams struct {
	Teapod   string
	Resource string
}

func (q *Queries) GetTea(ctx context.Context, arg GetTeaParams) (Tea, error) {
	row := q.db.QueryRowContext(ctx, getTea, arg.Teapod, arg.Resource)
	var i Tea
	err := row.Scan(
		&i.ID,
		&i.Teapod,
		&i.Collection,
		&i.Resource,
		&i.Value,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listTeas = `-- name: ListTeas :many
SELECT id, teapod, collection, resource, value, created, updated FROM teas WHERE teapod = ?
`

func (q *Queries) ListTeas(ctx context.Context, teapod string) ([]Tea, error) {
	rows, err := q.db.QueryContext(ctx, listTeas, teapod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tea
	for rows.Next() {
		var i Tea
		if err := rows.Scan(
			&i.ID,
			&i.Teapod,
			&i.Collection,
			&i.Resource,
			&i.Value,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTea = `-- name: UpdateTea :exec
UPDATE teas
set value = ?
WHERE teapod = ? and resource = ?
`

type UpdateTeaParams struct {
	Value    interface{}
	Teapod   string
	Resource string
}

func (q *Queries) UpdateTea(ctx context.Context, arg UpdateTeaParams) error {
	_, err := q.db.ExecContext(ctx, updateTea, arg.Value, arg.Teapod, arg.Resource)
	return err
}
